config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do 
    resources :users
    resources :customers
    resources :services
  end

  namespace :customers do
    resources :reservations
  end

  resources :dashboard

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

	belongs_to :barber, dependent: :destroy, class_name: "User", foreign_key: "barber_id"
	belongs_to :user , dependent: :destroy, class_name: "User", foreign_key: "user_id"
	
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/service.rb
class Service < ActiveRecord::Base
	
	validates :name, presence: true
	validates :points, presence: true
	validates :price, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations, class_name: "Reservation"
  has_many :appointments, class_name: "Reservation"
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController 
	
	before_filter :authenticate_admin!

	def authenticate_admin!
		return render_404 unless current_user.is_admin?
	end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::ApplicationController

	before_filter :set_service, only: [:edit, :update]

	def index
	end

	def new
		@service = Service.new
	end

	def create
		@service = Service.new service_params
	end

	def edit
	end

	def update
		if @service.update_attributes service_params
		
		else

		end
	end

	private
	def service_params
		params.require(:service).permit(:name, :description,
											:points)
	end

	def set_service
		@service = Service.find(params[:id])
	end

end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::ApplicationController

	before_filter :set_transaction, only: [:edit, :update]

	def index
	end

	def new
	end

	def create
		@transaction = Transaction.new transaction_params
		if @transaction.save
			flash[:notice] = 'Successfully created transaction'
			redirect_to transaction_admin_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
	end

	private
	def transaction_params
		params.require(:transaction).permit(:user_id, :barber_id)
	end

	def set_transaction
		@transaction = Transaction.find(params[:id])
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController 

	before_filter :set_user, only: [:update, :edit]

	def index
		@users = User.page(params[:page]).per(10)
	end

	def new
	end

	def create
		@user = User.new barber_params
		if @user.save
			flash[:notice] = 'Successfully save barber'
			redirect_to admin_barber_path
		else
			render 'new'
	end

	def edit
	end

	def update
		if @user.update_attributes barber_params
			flash[:notice] = 'Successfully updated barber'
			redirect_to admin_barber_path
		else 
			render 'edit'
		end
	end

	private
	def barber_params
		params.require(:user).permit(:email, :password,
										:password_confirmation)
	end

	def set_user
		@user = User.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/barbers/application_controller.rb
class Barbers::ApplicationController < ApplicationController
	
	before_filter :authenticate_barbers!

	def authenticate_barbers!
	end
end

app/controllers/barbers/reservations_controller.rb
class Barbers::ReservationsController < Barbers::ApplicationController

	def index
		@reservations = current_user.appointments.page(params[:page]).per(10)
	end
	
end

app/controllers/customers/application_controller.rb
class Customers::ApplicationController < ApplicationController

	before_filter :authenticate_customer!

	def authenticate_customer!

	end
end

app/controllers/customers/reservations_controller.rb
class Customers::ReservationsController < Customers::ApplicationController
	
	def index
		@reservations = current_user.reservations.page(params[:page]).per(10)
	end

	def new
		@reservation = Reservation.new
	end

	def create
		@reservation = Reservation.new reservation_params
		@reservation.user_id = current_user.id
		
		if @reservation.save
			flash[:notice] = 'Successfully created reservation'
			redirect_to customers_reservation_path
		else
			render 'new'
		end

	end

	def edit
	end

	def update
	end

	def destroy
	end

	private 
	def set_reservation
		@reservation = Reservation.find(params[:id])
	end

	def reservation_params
		params.require(:reservation).permit(:barber_id, :date, 
												:service_ids, :time)
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	
	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/services/_form.html.haml
= form_for [:admin, @service], html: { class: 'form-horizontal'} do |f|
	= render 'shared/error_messages', :object => f.object
	.row
		.col-md-12
			.form-group
				= f.label :name, class: 'control-label'
				.col-sm-8
					= f.text_field :name, class: 'form-control'
			.form-group
				= f.label :description, class: 'control-label'
				.col-sm-8
					= f.text_area :description, class: 'form-control'
			.form-group
				= f.label :points, class: 'control-label'
				.col-sm-8
					= f.text_field :points, class: 'form-control'
			.form-group
				= f.label :price, class: 'control-label'
				.col-sm-8
					= f.text_field :price, class: 'form-control'
	.form-actions
		= f.submit "Save", class: 'btn btn-sucess'

app/views/admin/services/edit.html.haml
%h1 Edit Service
%hr

= render 'form'

app/views/admin/services/index.html.haml
%h1 Services
%hr

.container
	.pull-right
		= link_to "New Service", new_admin_service_path, class: 'btn btn-success'

%table.table.table-striped
	%thead
		%th Name
		%th Price
		%th Points
		%th 
	%tbody
		- @services.each |service|
			%tr
				%td= service.name
				%td= service.price
				%td= service.points
				%td= link_to 'Edit', edit_admin_service_path(service), class: 'btn btn-success'

= paginate @services
= page_entries_info @services

app/views/admin/services/new.html.haml
%h1 New Service
%hr

= render 'form'

app/views/layouts/_flash.html.haml
.flash-container
	- if alert
		.flash-alert
			= alert
	- elsif notice
		.flash-notice
			= notice

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barbers Reservation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/flash' %>

<div class="container">
	<%= yield %>
</div>

<%= yield :scripts %>
</body>
</html>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
	.alert.alert-danger.danger-dismissable
		%a.close{ :href => '#', "data-dismiss" => "alert" } &times
		%p= "The form contains #{pluralize(object.errors.count, 'error')}"
		%ul 
			- object.errors.full_messages.each do |msg|
				%li= msg